from pydantic import BaseModel, Field

class UserModel(BaseModel):
    user_id: int = Field(...)
    user_name: int = Field(...)
    donation_amount: int = Field(...)
    donation_cnt: int = Field(...)
    category_children: int = Field(...)
    category_oldman: int = Field(...)
    category_disabled: int = Field(...)
    category_multiculture: int = Field(...)
    category_global: int = Field(...)
    category_family: int = Field(...)
    category_animal: int = Field(...)
    category_environment: int = Field(...)


class LavelModel(BaseModel):
    donation_id: int = Field(...)
    user_id: int = Field(...)
    donation_date: int = Field(...)
    donation_time: int = Field(...)

class DonationModel(BaseModel):
    donation_id: int = Field(...)
    category_children: int = Field(...)
    category_oldman: int = Field(...)
    category_disabled: int = Field(...)
    category_multiculture: int = Field(...)
    category_global: int = Field(...)
    category_family: int = Field(...)
    category_animal: int = Field(...)
    category_environment: int = Field(...)
    donation_title: int = Field(...)
    donation_organization: int = Field(...)
    donation_img: int = Field(...)
    most_noun: int = Field(...)
    section1_title: int = Field(...)
    section1: int = Field(...)
    section2_title: int = Field(...)
    section2: int = Field(...)
    section3_title: int = Field(...)
    section3: int = Field(...)
    section4_title: int = Field(...)
    section4: int = Field(...)
    section5_title: int = Field(...)
    section5: int = Field(...)
    create_time: int = Field(...)
    end_time: int = Field(...)
    donation_amount: int = Field(...)
    donation_limit: int = Field(...)
    donation_target: int = Field(...)
    donation_cnt: int = Field(...)